# Generated by Django 5.0.3 on 2024-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
