# Generated by Django 5.0.3 on 2024-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('certificatePDF', models.FileField(upload_to='media/certificate_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAndKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/skill_and_knowledge_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
