# Generated by Django 5.0.3 on 2024-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curriculum',
            field=models.FileField(unique=True, upload_to='media/profile_pdf_curriculum/'),
        ),
    ]
