# Generated by Django 5.0.3 on 2024-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_profile_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(max_length=100),
        ),
    ]
