# Generated by Django 5.0.3 on 2024-06-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_certificates_description_alter_profile_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='certificatePDF',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='description',
        ),
        migrations.AddField(
            model_name='certificates',
            name='certificateIMG',
            field=models.URLField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='curriculum',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(),
        ),
    ]
