# Generated by Django 5.0.6 on 2024-06-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_certificateimg_certificates_certificatepdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='organizer',
            field=models.CharField(default='default_organizer', max_length=50),
            preserve_default=False,
        ),
    ]
